[package]
name = "angry_bevys"
version = "0.1.0"
edition = "2024"

[dependencies]
avian2d = "0.3.1"
bevy = { version = "0.16.1", features = ["default_font"] }
bevy_asset_loader = "0.23.0"
bevy_egui = "0.36.0"
